### PR TITLE
Fix ordering in the least bad way possible maybe (fixes #38)

### LINKED ISSUE #38: Ordering for `Set` and `Map` is not what's expected
See [comment](https://github.com/udoprog/fixed-map/pull/37#issuecomment-1292875661).

This primarily stems from how the ordering implementation for `Option` is derived:

```rust
#[derive(PartialEq, PartialOrd)]
enum Foo {
    First,
    Second,
}

fn main() {
    assert!(Foo::First < Foo::Second);
    assert!([Some(Foo::First), None] > [None, Some(Foo::Second)]);
}
```

Without such a definition, some form of wrapper would be needed to change how ordering is done. But any such abstractions also cause issues with potential optimization opportunities.

However it's done, it will become part of the public API of this crate.

### PR DESCRIPTION
**Pull request by udoprog**
This re-implements `Iterator::partial_cmp_by` and `Iterator::cmp_by` (since those are not stable yet) and re-exports their use in macros. Once those are stable, all we need to export is the comparison function.

I've decided to specialize these functions as much as possible, it's possible to make `a` and `b` into `IntoIterator`, but since they'll never be used this way this ensures that Rust has to do as little work as possible to optimize their use.

I've also separated out the comparison functions (`__storage_option_partial_cmp`, `__storage_option_cmp`) for two reasons: they can be used once the `Iterator` functions are stable and they will be used when implementing ordering for any variants (which uses immediate `Option<V>` fields).

### CODE REVIEW

**Comment by pitaj** [comment]
I'd recommend adding a bunch more tests, with more than two elements. I think the current implementation may have the same issues as this: https://github.com/udoprog/fixed-map/issues/38#issuecomment-1294078269

**Comment by udoprog** [comment]
Yeah, that makes sense. I'll double check and/or fix the behavior. Cheers!

**Comment by udoprog** [comment]
I've adopted roughly the solution that you used in [this comment](https://github.com/udoprog/fixed-map/issues/38#issuecomment-1294062006). I'm keeping the functions (but making them generic again :D) to keep the macro expansion a bit more chill.

Thanks for giving me a hand with this!

File: src/macro_support.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+fn flatten<T>(value: (usize, &Option<T>)) -> Option<(usize, &T)> {
+    match value {
+        (index, Some(value)) => Some((index, value)),
+        _ => None,
+    }
+}
+
+/// `partial_cmp` implementation over iterators which ensures that storage
+/// ordering between `None` and `Some` is handled in a reasonable manner.
+#[doc(hidden)]
```
Comment (pitaj) [inline src/macro_support.rs]: Don't think these need to be `doc(hidden)` since the module is. Might want to copy the following private API warning from option_bucket to this module as well:

```
//! # PRIVATE API
//!
//! This API is private, for use only in the `derive(Key)` macro.
//! Usage for other purposes is not supported, and this API will
//! not abide by Semver stability guarantees.
```

File: src/macro_support.rs [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+#[allow(clippy::missing_inline_in_public_items)]
```
Comment (pitaj) [inline src/macro_support.rs:19]: Why not mark these as `#[inline]`?

File: fixed-map-derive/src/unit_variants.rs [hunk 3]
```diff
@@ -192,53 +194,15 @@ pub(crate) fn implement(cx: &Ctxt<'_>, en: &DataEnum) -> Result<TokenStream, ()>
             impl<V> #partial_ord_t for Storage<V> where V: #partial_ord_t {
```
Comment (pitaj) [inline fixed-map-derive/src/unit_variants.rs:194]: `PartialOrd` and `Ord` should probably require that the key type implement the same, even though it isn't strictly necessary for the implementation.

You can achieve this by adding the following additional bound to the where clause (workaround for trivial bounds in where clauses):
```
#ident: for<#lt> #partial_ord_t,
```

Comment (udoprog) [reply fixed-map-derive/src/unit_variants.rs:194]: Well, I don't think it's a *great* idea since it gives the wrong impression about ordering: that you can implement `PartialOrd` to decide how something is ordered when that isn't possible.

It's better to indicate to the user of the library that the `Key` trait comes with its own ordering semantics. Or in the case where it's backed by a `HashMap` simply isn't ordered (but this would have to be solved later).

File: src/macro_support.rs (hunk 2 above)
Comment (udoprog) [reply src/macro_support.rs:19]: The reasoning was that it's a big function body (once all the calls are expanded). It's probably better to let Rust decide what shouldn't and should be inlined with a slight preference towards code re-use to avoid codegen bloat.

I plan to do some comparisons later both with speed and code size.

File: src/macro_support.rs (hunk 1 above)
Comment (udoprog) [reply src/macro_support.rs]: Added the warning instead. Cheers!

File: fixed-map-derive/src/unit_variants.rs (hunk 3 above)
Comment (udoprog) [reply fixed-map-derive/src/unit_variants.rs:194]: As a (maybe temporary) compromise: how derived ordering semantics should at least be documented on the `Key` trait and linked to in the collection's `PartialOrd` and `Ord` impls.

File: src/macro_support.rs (hunk 2 above)
Comment (pitaj) [reply src/macro_support.rs:19]: It's a generic function, so implicitly inline-able anyways.

Comment (udoprog) [reply src/macro_support.rs:19]: Ah, so to my understanding generic functions aren't inherently more inline-able than regular functions. What I think will happen is that any calls to this function which has a compatible set of type parameters will re-use the same underlying implementation *unless* rustc decides that it's better to inline it.

E.g. 3 uses but two functions: https://godbolt.org/z/383PY65vW

This is just an instance where I think the generated function is *kinda* large. So I'd rather hint that it should use its regular heuristics rather than inline it to encourage code re-use.
